[tool.poetry]
name = "abot"
version = "0.1.0"
description = ""
authors = ["djkcyl <cyl@cyllive.cn>"]

[tool.poetry.dependencies]
python = "3.8"
graia-application-mirai = "0.19.2"
graia-broadcast = "0.8.11"
graia-saya = "^0.0.9"
graia-scheduler = "^0.0.4"
requests = "^2.26.0"
Pillow = "^8.3.1"
numpy = "^1.21.1"
matplotlib = "^3.4.2"
wordcloud = "^1.8.1"
pkuseg = "^0.0.25"
dnspython = "^2.1.0"
moviepy = "^1.0.3"
pydantic = "1.7.1"
peewee = "^3.14.4"
PyMySQL = "^1.0.2"
PixivPy = "^3.5.11"
func-timeout = "^4.3.5"
graiax-silkcoder = "^0.0.14"
httpx = "^0.18.2"
playwright = "^1.12.1"
lxml = "^4.6.3"
PyYAML = "^5.4.1"
interval = "^1.0.0"
tencentcloud-sdk-python = "^3.0.454"
xmltodict = "^0.12.0"
azure-cognitiveservices-speech = "^1.18.0"
redis = "^3.5.3"
pyzbar = "^0.1.8"
qrcode = "^7.2"
rsa = "^4.7.2"
pyacrcloud = "^1.0.2"

[tool.poetry.dev-dependencies]
autopep8 = "^1.5.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "douban"
url = "https://pypi.doubanio.com/simple"
default = true