[tool.poetry]
name = "abot-mahv2"
version = "2.2.0"
description = ""
authors = ["djkcyl <cyl@cyllive.cn>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
graia-broadcast = "^0.13.1"
graia-saya = "^0.0.13"
Pillow = "^8.4.0"
numpy = "^1.21.4"
matplotlib = "^3.4.2"
wordcloud = "^1.8.1"
dnspython = "^2.1.0"
peewee = "^3.14.4"
PyMySQL = "^1.0.2"
func-timeout = "^4.3.5"
graiax-silkcoder = "^0.0.19"
httpx = "^0.20.0"
playwright = "^1.16.0"
lxml = "^4.6.4"
PyYAML = "^5.4.1"
tencentcloud-sdk-python = "3.0.520"
xmltodict = "^0.12.0"
azure-cognitiveservices-speech = "^1.19.0"
redis = "^3.5.3"
pyzbar = "^0.1.8"
qrcode = "^7.2"
rsa = "^4.7.2"
pyacrcloud = "^1.0.2"
prettytable = "^2.4.0"
jieba = "^0.42.1"
psutil = "^5.8.0"
markdown = "^3.3.4"
scipy = "^1.7.2"
pillow = "^8.4.0"
saucenao-api = "^2.4.0"
triangler = {git = "https://github.com/djkcyl/triangler"}
graia-ariadne = "^0.4.0"
graia-scheduler = "^0.0.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.dev-dependencies]
devtools = "^0.8.0"
black = "^21.10b0"
flake8 = "^4.0.1"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true